import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { complete } from '@/lib/ai/llm';

export const maxDuration = 60; // Max timeout on Vercel Hobby

const SAMPLE_PAPER_SYSTEM_PROMPT = `You are an expert exam designer and academic professor.
Your task is to generate a custom practice exam / sample paper based on the provided syllabus and study notes.

RULES:
- Generate questions matching the format requested by the user EXACTLY (e.g. dividing into Section A, Section B, Section C).
- The questions must cover the topics listed in the syllabus.
- Use the provided study notes as the primary source of truth if available, to make the questions highly relevant.
- For each question, provide:
  1. A clear question text.
  2. A detailed answer key / sample answer.
  3. The marks allocated for the question (e.g. 5 marks or 2 marks).
  4. The section code it belongs to (e.g. "A", "B" or "C").
- Return the response as a JSON object matching this structure EXACTLY:
  {
    "title": "Sample Paper Title",
    "questions": [
      {
        "id": "q1",
        "question": "Question text here?",
        "answer_key": "Detailed correct answer or answer key.",
        "marks": 5,
        "section": "A"
      }
    ]
  }
`;

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: syllabusId } = await params;
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { format_description, title } = body;
    const customApiKey = request.headers.get('x-groq-api-key') || undefined;

    if (!format_description) {
      return NextResponse.json({ error: 'format_description is required' }, { status: 400 });
    }

    // 1. Fetch syllabus details
    const { data: syllabus, error: syllabusError } = await supabase
      .from('syllabi')
      .select('*')
      .eq('id', syllabusId)
      .eq('user_id', user.id)
      .single();

    if (syllabusError || !syllabus) {
      return NextResponse.json({ error: 'Syllabus not found' }, { status: 404 });
    }

    // 2. Fetch syllabus topics
    const { data: topics, error: topicsError } = await supabase
      .from('syllabus_topics')
      .select('*')
      .eq('syllabus_id', syllabusId)
      .eq('user_id', user.id)
      .order('sort_order', { ascending: true });

    if (topicsError || !topics) {
      return NextResponse.json({ error: 'Failed to fetch syllabus topics' }, { status: 500 });
    }

    // 3. Fetch any notes generated for these topics
    const noteIds = topics.map((t) => t.note_id).filter(Boolean) as string[];
    let notesContent = '';

    if (noteIds.length > 0) {
      const { data: notes } = await supabase
        .from('notes')
        .select('title, content')
        .in('id', noteIds);

      if (notes && notes.length > 0) {
        notesContent = notes
          .map((n) => `--- Notes for "${n.title}" ---\n${n.content}`)
          .join('\n\n');
      }
    }

    // 4. Construct user prompt for the LLM
    const syllabusDetailsText = topics
      .map((t, idx) => `${idx + 1}. ${t.title}: ${t.description || 'No description'}`)
      .join('\n');

    const userPrompt = `I need a practice paper for the course: "${syllabus.title}".
Here is the syllabus topics structure:
${syllabusDetailsText}

Here is the context from notes we have studied so far (if empty, use general academic knowledge for this course):
${notesContent || 'No notes available yet.'}

Requested Format:
${format_description}

Please generate the sample paper in the required JSON format.`;

    // 5. Call LLM to generate the exam
    const response = await complete(
      [
        { role: 'system', content: SAMPLE_PAPER_SYSTEM_PROMPT },
        { role: 'user', content: userPrompt },
      ],
      {
        temperature: 0.5,
        maxTokens: 3000,
        jsonMode: true,
        model: 'llama-3.3-70b-versatile',
        apiKey: customApiKey,
      }
    );

    let parsedPaper: { title: string; questions: any[] };
    try {
      parsedPaper = JSON.parse(response);
    } catch (e) {
      console.error('Failed to parse practice paper JSON:', response);
      return NextResponse.json({ error: 'AI failed to generate a structured practice paper.' }, { status: 500 });
    }

    const paperTitle = title || parsedPaper.title || `Sample Paper for ${syllabus.title}`;
    const questions = parsedPaper.questions || [];

    if (questions.length === 0) {
      return NextResponse.json({ error: 'No questions were generated by the AI.' }, { status: 400 });
    }

    // 6. Save sample paper to the database
    const { data: paperRecord, error: insertError } = await supabase
      .from('sample_papers')
      .insert({
        syllabus_id: syllabusId,
        user_id: user.id,
        title: paperTitle,
        format_description,
        content: questions,
      })
      .select()
      .single();

    if (insertError || !paperRecord) {
      console.error('Sample paper insert error:', insertError);
      return NextResponse.json({ error: 'Failed to save sample paper' }, { status: 500 });
    }

    return NextResponse.json({ data: paperRecord });
  } catch (error) {
    console.error('Sample paper generation route error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: syllabusId } = await params;
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { data: papers, error } = await supabase
      .from('sample_papers')
      .select('*')
      .eq('syllabus_id', syllabusId)
      .eq('user_id', user.id)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Sample papers fetch error:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ data: papers });
  } catch (error) {
    console.error('Sample papers GET error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
