'use client';

import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen py-16 px-4 relative flex items-center justify-center">
      {/* Background orbs */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-0 right-0 w-80 h-80 rounded-full opacity-10"
          style={{ background: 'radial-gradient(circle, hsl(255 85% 68%), transparent)' }} />
      </div>

      <div className="w-full max-w-3xl animate-fade-in">
        {/* Header */}
        <div className="text-center mb-8">
          <Link href="/" className="inline-flex items-center gap-2 mb-6">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center text-lg text-white"
              style={{ background: 'linear-gradient(135deg, hsl(255 85% 68%), hsl(280 70% 65%))' }}>
              ⚡
            </div>
            <span className="font-bold text-lg gradient-text">Synap™</span>
          </Link>
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="text-muted-foreground mt-1">Last Updated: May 26, 2026</p>
        </div>

        {/* Content Card */}
        <div className="glass rounded-2xl p-8 md:p-10 border border-border space-y-6 text-sm text-muted-foreground leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Synap (<strong>https://www.synap.bond</strong>), you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">2. Use License & Service Quota</h2>
            <p>
              Synap is an AI-powered study assistant designed to compile detailed notes, flashcards, and quizzes from academic files and YouTube videos.
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Free Quota:</strong> Every user is permitted up to 2 high-quality note generations per calendar day under our default free plan.</li>
              <li><strong>Abuse Prevention:</strong> You may not attempt to automate note requests, script account registrations, or reverse engineer our segment coordinator pipelines.</li>
              <li><strong>Custom Keys:</strong> If you input your own custom Groq API Key, you are responsible for any token rate limits or costs associated with your personal Groq account.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">3. User Content Responsibility</h2>
            <p>
              You retain all rights to the lecture transcripts, PDFs, and audio recordings you submit to Synap. However, you are solely responsible for ensuring that you have the legal right or academic permissions to upload and transcribe the content you submit. Synap is not liable for any copyright infringements resulting from user-submitted lectures.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">4. Disclaimer of AI Content</h2>
            <p>
              The study notes, summaries, definitions, and flashcards generated by Synap are compiled using state-of-the-art large language models. While we strive for extreme detail and reasoning accuracy, AI-generated content can occasionally contain inaccuracies or "hallucinations." Synap does not guarantee the absolute correctness of generated notes and is not responsible for academic grades or performance.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">5. Service Modifications</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue any aspect of Synap at any time without notice. We also reserve the right to update these Terms of Service. Your continued use of the website following any changes indicates your acceptance of the updated terms.
            </p>
          </section>

          <div className="pt-6 border-t border-border flex justify-between items-center text-xs">
            <Link href="/login" className="text-primary hover:underline font-medium">
              &larr; Back to Sign In
            </Link>
            <Link href="/privacy" className="text-muted-foreground hover:text-foreground transition-colors">
              Privacy Policy &rarr;
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
